### ISSUE TITLE
Garden lights not implemented

### ISSUE THREAD

**Issue by rzippo** [MeloniZippoProjects/nesProject#10]
Finally, the user also has the possibility to switch on and switch off the lights in the garden
. This is done  by  directly  pressing the button  of  Node1.  The  garden  lights  are  on  when  the 
green  LED of Node1  is  on,  and the red one  is  off.  Vice  versa, the  garden  lights  are off  when  the  red  LED  is  on, and the green one is off.

**Comment by enricomeloni** [comment]
I take this

**Comment by enricomeloni** [comment]
Completed
