### ISSUE TITLE
Motion light control system

### ISSUE THREAD

**Issue by rzippo** [MeloniZippoProjects/nesProject#2]
Each door has two nodes representing the two directions of movement. The motion sensing is abstracted as the clicking of the corresponding button.
These nodes communicate with the LightControllers of the adjacent rooms, which will keep a counter (>=0) for the number of people that are supposed to be in the room. If the controller is in automatic mode, the lights are switched on when counter > 0, off otherwise.

**Comment by enricomeloni** [comment]
If the light sensor of the LightController measures a light level above a certain treshold, then even if the automatic mode is set, the lights won't be turned on.
